#
# GreatImpostor config
#


# This is the location everyone starts at during the beginning of a game or after the end of a meeting.
# Also, this is the location where everyone is teleported to during a meeting.
starting-location:
  world-name: world
  x: 0.0
  y: 256.0
  z: 0.0


# This is a vent system.
# Example:
#vents:
#  - - [-10.0, 25.0, 0.5]  # one vent system, and the coordinates of the vent
#    - [0.5, 25.0, 0.5]  # coordinates of a second vent in the first system
#    - [10.5, 25.0, 0.5]  # coordinates of a third vent in the first system
#
#  - - [0.5, 25.0, -10.5]  # a second vent system
#    - [0.5, 25.0, 10.5, 90.0]  # coordinates of a second vent in the second system
#                               # optionally, you can add a fourth number to specify the player's rotation/yaw
vents: []


# The list of the coordinates to teleport to when viewing security cameras
# Example:
#cameras:
#  - [5.5, 25.0, 5.5, -90.0]  # (the rotation/yaw is optional)
#  - [15.5, 25.0, 15.5]
cameras: []


# Number of ticks a meeting lasts.
# Default is 2100 ticks (1:45)
meeting-time-ticks: 2100


# Number of ticks you have to fix a critical sabotage (reactor, oxygen)
# Default is 600 ticks (30 seconds)
critical-sabotage-fix-ticks: 600


# Maximum number of meetings each player can call during a game.
# Default is 1 in the original game.
max-meetings-per-player: 1


# Whether the communications sabotage prevents body reporting. It does not in the original game, but I added this option
# if you want to buff the sabotage slightly.
comms-sabotage-prevents-reporting: false


# You can customize the impostor cooldowns here, and there's finer control over each scenario (on game start, after
# actually using it, and after the game resumes after a meeting ends).
# The defaults are what they are in the main game: 10 second cooldown at the start of the game and 30 seconds after
# actually using it or a meeting
impostor-cooldowns:
  # How long before killing when the game starts (in ticks, default: 200t/10s)
  kill-game-start: 200
  # How long before sabotaging when the game starts (default: 200t/10s)
  sabotage-game-start: 200
  # How long before killing after killing (default: 600t/30s)
  kill-after-use: 600
  # How long before sabotaging after sabotaging (default: 600t/30s)
  sabotage-after-use: 600
  # How long before killing after a meeting ends (default: 600t/30s)
  kill-after-meeting: 600
  # How long before sabotaging after a meeting ends (default: 600t/30s)
  sabotage-after-meeting: 600


# Put the coordinates of the signs for each of the sabotage tasks here.
# The format is [X, Z].
sabotage-fix-coordinates:
  # Only 1 set of coordinates for the reactor; it is suggested you just set this to one of the two signs
  reactor: [0.5, 0.5]
  oxygen-in-oxygen: [0.5, 0.5]
  oxygen-in-admin: [0.5, 0.5]


# This is for debug only. You should always leave this on.
enable-victory-checks: true
