#
# GreatImpostor config
#


# This is the location everyone starts at during the beginning of a game or after the end of a meeting.
# Also, this is the location where everyone is teleported to during a meeting.
starting-location:
  world-name: world
  x: 0.0
  y: 256.0
  z: 0.0


# This is a vent system.
# Example:
#vents:
#  - - [-10.0, 25.0, 0.5]  # one vent system, and the coordinates of the vent
#    - [0.5, 25.0, 0.5]  # coordinates of a second vent in the first system
#    - [10.5, 25.0, 0.5]  # coordinates of a third vent in the first system
#
#  - - [0.5, 25.0, -10.5]  # a second vent system
#    - [0.5, 25.0, 10.5]  # coordinates of a second vent in the second system
vents: []


# The list of the coordinates to teleport to when viewing security cameras
# Example:
#cameras:
#  - [5.5, 25.0, 5.5]
#  - [15.5, 25.0, 15.5]
cameras: []


# Number of ticks a meeting lasts.
# Default is 2100 ticks (1:45)
meeting-time-ticks: 2100


# Number of ticks you have to fix a critical sabotage (reactor, oxygen)
# Default is 600 ticks (30 seconds)
critical-sabotage-fix-ticks: 600


# Maximum number of meetings each player can call during a game.
# Default is 1 in the original game.
max-meetings-per-player: 1


# Put the coordinates of the signs for each of the sabotage tasks here.
# The format is [X, Z].
sabotage-fix-coordinates:
  # Only 1 set of coordinates for the reactor; it is suggested you just set this to one of the two signs
  reactor: [0.5, 0.5]
  oxygen-in-oxygen: [0.5, 0.5]
  oxygen-in-admin: [0.5, 0.5]


# This is for debug only. You should always leave this on.
enable-victory-checks: true
