name: GreatImpostor
version: '${project.version}'
main: io.github.greatericontop.greatimpostor.GreatImpostorMain
api-version: 1.19
authors: [greateric]

softdepend: [PlaceholderAPI]

commands:
  impostor:
    description: GreatImpostor command
    usage: "§eTutorial: §b/impostor tutorial  §7|  §eStart game: §b/impostor start <number of impostors>"
  vote:
    description: GreatImpostor Vote command
    usage: "§eVote: §b/vote <player>  §7|  §eSkip vote: §b/vote skip"

permissions:
  impostor.admin:
    description: GreatImpostor admin
    default: op