name: GreatImpostor
version: '${project.version}'
main: io.github.greatericontop.greatimpostor.GreatImpostorMain
api-version: 1.19
authors: [greateric]

softdepend: [PlaceholderAPI]

commands:
  impostor:
    description: GreatImpostor command
    usage: /impostor <...>
    permission: impostor.command
  vote:
    description: GreatImpostor Vote command
    usage: "§eVote: §b/vote <player>  §7|  §eSkip vote: §b/vote skip"
    permission: impostor.vote