name: GreatImpostor
version: '${project.version}'
main: io.github.greatericontop.greatimpostor.GreatImpostorMain
api-version: 1.19
authors: [greateric]

softdepend: [PlaceholderAPI]

commands:
  impostor:
    description: GreatImpostor command
    permission: impostor.command