package io.github.greatericontop.greatimpostor.task;

public enum SubtaskType {

    WIRING_ELECTRICAL,
    WIRING_STORAGE,
    WIRING_ADMIN,
    WIRING_NAVIGATION,
    WIRING_CAFETERIA,
    WIRING_SECURITY,

    REDIRECT_POWER,
    ACCEPT_POWER_COMMUNICATIONS,
    ACCEPT_POWER_LOWER_ENGINE,
    ACCEPT_POWER_UPPER_ENGINE,
    ACCEPT_POWER_NAVIGATION,
    ACCEPT_POWER_OXYGEN,
    ACCEPT_POWER_SECURITY,
    ACCEPT_POWER_SHIELDS,
    ACCEPT_POWER_WEAPONS,

}
