package io.github.greatericontop.greatimpostor.task;

public enum Subtask {

    WIRING_ELECTRICAL(TaskType.WIRING),
    WIRING_STORAGE(TaskType.WIRING),
    WIRING_ADMIN(TaskType.WIRING),
    WIRING_NAVIGATION(TaskType.WIRING),
    WIRING_CAFETERIA(TaskType.WIRING),
    WIRING_SECURITY(TaskType.WIRING),

    REDIRECT_POWER(TaskType.REDIRECT_ACCEPT_POWER),

    ACCEPT_POWER_COMMUNICATIONS(TaskType.REDIRECT_ACCEPT_POWER),
    ACCEPT_POWER_LOWER_ENGINE(TaskType.REDIRECT_ACCEPT_POWER),
    ACCEPT_POWER_UPPER_ENGINE(TaskType.REDIRECT_ACCEPT_POWER),
    ACCEPT_POWER_NAVIGATION(TaskType.REDIRECT_ACCEPT_POWER),
    ACCEPT_POWER_OXYGEN(TaskType.REDIRECT_ACCEPT_POWER),
    ACCEPT_POWER_SECURITY(TaskType.REDIRECT_ACCEPT_POWER),
    ACCEPT_POWER_SHIELDS(TaskType.REDIRECT_ACCEPT_POWER),
    ACCEPT_POWER_WEAPONS(TaskType.REDIRECT_ACCEPT_POWER),

    DOWNLOAD_DATA_CAFETERIA(TaskType.DOWNLOAD_UPLOAD_DATA),
    DOWNLOAD_DATA_COMMUNICATIONS(TaskType.DOWNLOAD_UPLOAD_DATA),
    DOWNLOAD_DATA_ELECTRICAL(TaskType.DOWNLOAD_UPLOAD_DATA),
    DOWNLOAD_DATA_NAVIGATION(TaskType.DOWNLOAD_UPLOAD_DATA),
    DOWNLOAD_DATA_WEAPONS(TaskType.DOWNLOAD_UPLOAD_DATA),

    UPLOAD_DATA(TaskType.DOWNLOAD_UPLOAD_DATA),

    ;

    private final TaskType fullTask;

    Subtask(TaskType fullTask) {
        this.fullTask = fullTask;
    }

    public TaskType getFullTask() {
        return fullTask;
    }

}
